name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: ttpp_testing
          MYSQL_ROOT_PASSWORD: ttpp_password
        ports:
          - 3306:3306
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - uses: actions/checkout@v4
      - name: Init .env
        run: ln -f -s .env.pipelines .env
      - name: Install Dependencies
        run: composer install --ignore-platform-reqs
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Run migrations
        run: php artisan migrate:fresh
      - name: Run unit tests
        run: vendor/bin/phpunit
      - name: Run Gerkin tests
        run: vendor/bin/behat
